# Generated by Django 3.2.5 on 2022-03-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='func_log',
            name='is_worked',
            field=models.IntegerField(default=0),
        ),
    ]
